/**
 * Server-only exports — LangGraph Annotation.Root state definitions.
 * These depend on @langchain/langgraph which is a server-side dependency.
 * Import via "@langgraph-fix-issues-pipeline/shared/server".
 */

import { Annotation } from "@langchain/langgraph";
import type { TIssueIntake, TIssuePlan, TCoderResult, TReviewResult, TPipelineResult } from "./issue.js";
export type { TIssueIntake, TIssuePlan, TCoderResult, TReviewResult, TPipelineResult } from "./issue.js";

/**
 * Issue Pipeline graph state.
 */
export const IssuePipelineState = Annotation.Root({
  /** Raw issue text */
  inputText: Annotation<string>({
    reducer: (x, y) => y ?? x ?? "",
    default: () => "",
  }),
  /** Structured issue intake result */
  issue: Annotation<TIssueIntake | null>({
    reducer: (x, y) => y ?? x ?? null,
    default: () => null,
  }),
  /** Pipeline result with collected errors */
  result: Annotation<TPipelineResult>({
    reducer: (x, y) => y ?? x ?? { errors: [] },
    default: () => ({ errors: [] }),
  }),
  /** Number of issue intake attempts (for conditional retry) */
  issueIntakeAttempts: Annotation<number>({
    reducer: (x, y) => y ?? x ?? 0,
    default: () => 0,
  }),
  /** Implementation plan generated by the plan node */
  plan: Annotation<TIssuePlan | null>({
    reducer: (x, y) => y ?? x ?? null,
    default: () => null,
  }),
  /** Result from the coder node */
  coderResult: Annotation<TCoderResult | null>({
    reducer: (x, y) => y ?? x ?? null,
    default: () => null,
  }),
  /** Number of coder attempts (for conditional retry) */
  coderAttempts: Annotation<number>({
    reducer: (x, y) => y ?? x ?? 0,
    default: () => 0,
  }),
  /** Result from the review node */
  reviewResult: Annotation<TReviewResult | null>({
    reducer: (x, y) => y ?? x ?? null,
    default: () => null,
  }),
  /** Number of review attempts (for conditional retry) */
  reviewAttempts: Annotation<number>({
    reducer: (x, y) => y ?? x ?? 0,
    default: () => 0,
  }),
});

export type TIssuePipelineGraphState = typeof IssuePipelineState.State;
